import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>MBA Engineering Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="flex font-extrabold font-sans underline">Hello world!</h1>
    </>
  );
}
